- name: create jenkins jobs
  hosts: localhost
  roles:
    -jenkins
  vars:
    mjobs:
      - { job_name: "cart", repo_name: "https://github.com/Gorthivani/cart.git"}

    sjobs:
      - { job_name: "roboshop-terraform", repo_name: "https://github.com/Gorthivani/roboshop-terraform" }