- name: copy  configuration file - {{item.job_name}}
  ansible.builtin.template:
    src: mjob.xml
    dest: /tmp/mjob.xml

- name: Create a jenkins job - {{item.job_name}}
  community.general.jenkins_job:
    config: "{{ lookup('file', 'tmp/mjob.xml') }}"
    name: "{{ item.job_name }}"
    password: admin123
    url: http://34.229.19.68:8080
    user: admin