- name: copy  configuration file
  ansible.builtin.template:
    src: sjob.xml
    dest: /tmp/sjob.xml

- name: Create a jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', 'tmp/sjob.xml') }}"
    name: "{{ item.job_name}}"
    password: admin123
    url: http://34.229.19.68:8080
    user: admin